services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    ports:
      - '3000:3000'
    environment:
      - NEXT_DISABLE_LIGHTNINGCSS=1
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    # ホットリロードのためにホストのファイル変更を監視
    stdin_open: true
    tty: true
